spring:
  datasource:
    url: jdbc:mysql://mysql:3306/envios_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8087
servicios:
  pedidos:
    url: http://order-service:8085
