CREATE TABLE cupones (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    monto_minimo DECIMAL(10, 2),
    usos_maximos INT NOT NULL,
    usos_actuales INT NOT NULL DEFAULT 0,
    fecha_expiracion TIMESTAMP NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
