spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
logging:
  level:
    org.springframework: INFO
    com.VentaOnline.OrderService: DEBUG
  file:
    name: logs/order-service.log
